# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colNorm <- function(G) {
    .Call('_mashr_colNorm', PACKAGE = 'mashr', G)
}

proj_gauss_mixtures_IDL <- function(ydatavec, ycovarvec, projectionvec, logweightsvec, N, dy, ampvec, xmeanvec, xcovarvec, d, K, fixampvec, fixmeanvec, fixcovarvec, avgloglikedatavec, tol, maxiter, likeonly, w, logfilenamevec, slen, splitnmerge, convlogfilenamevec, convloglen, noproj, diagerrs, noweight) {
    .Call('_mashr_proj_gauss_mixtures_IDL', PACKAGE = 'mashr', ydatavec, ycovarvec, projectionvec, logweightsvec, N, dy, ampvec, xmeanvec, xcovarvec, d, K, fixampvec, fixmeanvec, fixcovarvec, avgloglikedatavec, tol, maxiter, likeonly, w, logfilenamevec, slen, splitnmerge, convlogfilenamevec, convloglen, noproj, diagerrs, noweight)
}

calc_lik_rcpp <- function(b_mat, s_mat, v_mat, l_mat, U_3d, logd, common_cov) {
    .Call('_mashr_calc_lik_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, l_mat, U_3d, logd, common_cov)
}

calc_post_rcpp <- function(b_mat, s_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type) {
    .Call('_mashr_calc_post_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type)
}

